### ISSUE TITLE
Remove line continuation chars

### ISSUE THREAD

**Issue by kiryph** [sk1418/Join#1]
Many programming languages offer the possibility to break a line with the help of a line continuation character.

When I usually join those lines, I have to remove this line continuation character manually.

Maybe, your plugin could help me out here.

What do you think?

Note, vimscript adds the line continuation character at the beginning of the new line, c and shell scripting languages at the end of the previous line.

**Comment by sk1418** [comment]
thanks for the suggestion.

So far the Join cannot join lines and remove some trailing patterns.  Joining with separator (reverse/forward) is more often (subjective opinion) use cases. For example, from lines of text to build a string array format etc.

So far I haven't plan to implement the "join and remove separator" - like function. However for your requirement, it is easy to do with `:s` command, if you need it very often, you can declare a customer command/mapping/macro in your vimrc.

say, we have:

       ..... other codes
	2	foo bar codes {.... _
	3   blah . . . . _
	4	blah .... _
	5	ends here }
       ..... other codes
You can just visual select (by `V`) line `2-4`, then do:

	:s/_\n/ /

After that the text will be turned into:

	foo bar codes {....    blah . . . .  blah ....  ends here }

When you typed `:`, vim will automatically fill range `'<,'>`. 

You may want to remove the indentation too, you can do with the `:s` as well.

Hope it helps.

**Comment by kiryph** [comment]
Thanks for your detailed answer. However, I overlooked that the plugin splitjoin by Andrew Radev (https://github.com/AndrewRadev/splitjoin.vim) already supports removing line continuation in vimscript. So I think I should bother him with my question for a general support of removing line continuation characters in other languages.
